language: php

matrix:
  include:
    # 5.6
#    - php: 5.6
#      env: SYMFONY_VERSION=2.8.*
#    - php: 5.6
#      env: SYMFONY_VERSION=3.4.*
    # 7.0
#    - php: 7.0
#      env: SYMFONY_VERSION=2.8.*
#    - php: 7.0
#      env: SYMFONY_VERSION=3.4.*
    # 7.1
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
    - php: 7.1
      env: SYMFONY_VERSION=4.0.*
    # 7.2
    - php: 7.2
      env: SYMFONY_VERSION=2.8.*
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION=4.0.*
    # 7.3
    - php: 7.3
      env: SYMFONY_VERSION=2.8.*
    - php: 7.3
      env: SYMFONY_VERSION=3.4.*
    - php: 7.3
      env: SYMFONY_VERSION=4.0.*
    # hhvm
#    - php: hhvm
#      dist: trusty
#      env: SYMFONY_VERSION=2.8.*
#    - php: hhvm
#      dist: trusty
#      env: SYMFONY_VERSION=3.4.*

install:
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev symfony/symfony=$SYMFONY_VERSION; fi;'
  - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs -n -p --encoding=utf-8 --standard=PSR2 --extensions=php --ignore=vendor .
