language: php

matrix:
  include:
    # 7.2
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION=4.4.*
    # 7.3
    - php: 7.3
      env: SYMFONY_VERSION=3.4.*
    - php: 7.3
      env: SYMFONY_VERSION=4.4.*
    # 7.4
    - php: 7.4
      env: SYMFONY_VERSION=3.4.*
    - php: 7.4
      env: SYMFONY_VERSION=4.4.*
    - php: 7.4
      env: SYMFONY_VERSION=5.0.*
    # hhvm
#    - php: hhvm
#      dist: trusty
#      env: SYMFONY_VERSION=2.8.*
#    - php: hhvm
#      dist: trusty
#      env: SYMFONY_VERSION=3.4.*

install:
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev symfony/symfony=$SYMFONY_VERSION; fi;'
  - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs -n -p --encoding=utf-8 --standard=PSR2 --extensions=php --ignore=vendor .
